{% set name = "javafx-sdk" %}
{% set version = "12.0.2" %}
{% set number = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/javafxports/openjdk-jfx/archive/{{ version }}+{{ number }}.tar.gz
  sha256: 19a537129d9b2a66a9b7c2013297d8ef264f6106497c6d874db7782de1b65c8e
  patches:
    - linux.gradle.patch  # [linux]
    - mac.gradle.patch  # [osx]

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison
    - flex
    - gperf
    - pkgconfig
    - ant
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libpng-devel') }}  # [linux]
  host:
    - coreutils >=8
    - gtk2
    - pango
    - freetype
    - openjdk >=11
  run:
    - atk  # [linux]
    - cairo  # [linux]
    - fontconfig  # [linux]
    - gdk-pixbuf  # [linux]
    - glib  # [linux]
    - gtk2  # [linux]
    - pango  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxtst  # [linux]
    - font-ttf-dejavu-sans-mono # [linux]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test: 
  commands:
    - test -f "${PREFIX}/lib/${PKG_NAME}-${PKG_VERSION%}/lib/javafx.base.jar"

about:
  home: https://gluonhq.com/products/javafx/
  license: GPL-2.0 + Classpath
  license_file: LICENSE
  summary: 'JavaFX library for Java'
  description: |
    OpenJFX is an open source, next generation client application platform for desktop, mobile and embedded systems based on JavaSE. It is a collaborative effort by many individuals and companies with the goal of producing a modern, efficient, and fully featured toolkit for developing rich client applications.
  doc_url: https://openjfx.io/
  dev_url: https://github.com/javafxports/openjdk-jfx

extra:
  recipe-maintainers:
    - klugem
