travis:
  secure:
    BINSTAR_TOKEN: I+K/weQ0IQECVJrDZxB5X337hX6kkmqBA2Z6oaaafbwzYQb6bIAHeY2Cr3RZduwAjbuwiCOevXIkJEYsUnkJleC1DtFyMUG9S0LpSb0u+zPwRCPtWIStAsGgGntijlazPDnnPyb3ZBytPB4eyfIopYhQk8PjX9p1JvqEOMi8mjJehD+aKiFHuELHKEBe4yCQ+78EIaCn9KpaXCnmVGaI/VQ5+GWo3wVCLjmskR6O7SvXnT+KUs7Q4QL8pzDHkGsFmVBwT9oXRcgJiLdvrK5639cRA8zfb1sdBoRq0SX2XO6SAgfiS13Zx/ANkJtlePmArsmH1CbqB4/AHCzft8VNMONPuKZxdlGYq3yfK2+889mT8Zyl6DZb+RX9rWRLgqIkVRRv7j7jiHBMSzutn5cy/OQdy9R8uEG44jn41OhtL9zUME7YtLY3d2PNjoouyNpZnXEcP//9TYocCmFBYvh7ywxPDw1F5wC0DOqpQHEMkxFjrbcpuDLrnwtMF9fT3MRthVVtuNjOw0k2o+pfIg8k4aRsrVSCVm3R064xa5sHVJW2aF6RL1GNSgQEa06aLCXbrggIkgQRHpM3MHXzFimvLBTCKkNg4GHwcHvoxEkzryOYB6/pRoYsRQuMt9Wd1TYFYEBO5fvCZVjh/VmAO9owlo8Njyt2fXjbOe2ZPmt1e9M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
